---
output:
  html_document: 
    toc: true
    toc_float: true
---

## On the shoulders of giants

<link rel="stylesheet" href="styles.css" type="text/css">


In questa intervista al [New York times](https://www.nytimes.com/2009/01/07/technology/business-computing/07program.html?_r=3&), l'allora chief economist di Google, Hal Varian disse di R:
"The great beauty of R is that you can modify it to do all sorts of things, and you have a lot of prepackaged stuff that's already available, so....

> you're standing on the shoulders of giants"

Se hai un problema con i dati c'è un pachetto in R che te lo risolve. I pacchetti sono le unità fondamentali del codice R e permettono di ampliare le sue funzionalità.  

Un pacchetto raggruppa codice, dati, documentazione, test e fornisce un metodo semplice per condividerli con gli altri. Insomma, tutto quello che ti serve per essere operativo.

Questa enorme varietà di pacchetti è una delle ragioni per cui R ha così tanto successo: è probabile che qualcuno abbia già risolto un problema al quale stai lavorando, e che tu possa trarre vantaggio dal loro lavoro scaricando il loro pacchetto. C'è un pachetto per tutto; dai big data, al deep learning o come mettere in produzione il modello predittivo sviluppato. 
Per poter navigare al meglio all'interno delle funzionalità di R potete consultare la pagina [CRAN TASK VIEW](https://cran.r-project.org/web/views/). Al suo interno troverete la lista delle principali funzionalità con le relative librerie.
Ad oggi troviamo più di 12000 pachetti in [CRAN](https://cran.r-project.org/)

Oggi con R non fai solo analisi, ma si possono creare deliziose dashboard interattive web-based grazie al pachetto [shiny](https://shiny.rstudio.com/). 

Creare siti web. Tant'è che questo sito è interamente sviluppato con R, utilizzando [RStudio](https://www.rstudio.com/), la libreria [rmarkdown](https://rmarkdown.rstudio.com/rmarkdown_websites.html), la piattaforma [github](https://github.com/) e il fantastico tutorial di [Emily C. Zabor](http://www.emilyzabor.com/tutorials/rmarkdown_websites_tutorial.html) con il quale step-by-step sono stato guidato nella creazione del sito.


Se anche tu vorrai sfruttare al massimo la potenza di R dovrai imparare ad utilizzare al meglio le sue librerie. Se vuoi iniziare passa alla sezione [Let's Start](https://alessiopassalacqua.github.io/r-data-training/warmup.html), ti aiuterò a fare i primi passi in R e comprenderne le sue potenzialità.

## The Giants

Devi sapere anche che R è:

1.	integrato in numerose applicazioni sviluppate dai principali data providers: [Microsoft, Oracle, IBM, SAP, Tibco](http://blog.revolutionanalytics.com/2014/05/companies-using-r-in-2014.html)
2.	insegnato nelle [migliore università](https://pairach.com/2012/02/26/r-tutorials-from-universities-around-the-world/) di tutto il mondo come Stanford, Oxford, Harvard
3.	il più completo software per l'analisi dati: dalla stastistica di base al deep learning
4. Utlizzato dai giganti della [silicon valley](http://www.northeastern.edu/levelblog/2017/05/31/big-companies-using-r-data-analysis/)
 come [airbnb](http://blog.revolutionanalytics.com/2016/04/airbnb-uses-r.html), [google, twitter, facebook](http://blog.revolutionanalytics.com/2013/05/companies-using-open-source-r-in-2013.html), [uber](http://blog.revolutionanalytics.com/2014/06/more-companies-using-r.html)
 5. Usato dai giornalisti di [Finantial Times,  e BBC](http://blog.revolutionanalytics.com/2018/06/ft-bbc-uses-r.html) per raccontare notizie tramite visualizzazioni efficaci.

Se vuoi sapere di più ti consiglio questo articolo:

[11 Reasons Why You Should Learn R](https://stepupanalytics.com/11-reasons-why-you-should-learn-r/)

## Keep in touch

R nasce dall'idea di rendere l'analisi dati un processo ben definito, lineare e accessibile a tutti.Infatti la sua veloce diffusione è dovuta alla sua forza: la capacità di rendere semplice il processo di analisi dati. Con questo non voglio dire che R sia facile da imparare, tutt'altro. Voglio invece dire che l'analisi dati sarà facile ed elegante se imparerai ad utilizzare R.

Questo sito è dedicato a chi vuole iniziare ad usare R ed ha poca esperienza e conoscenza del mondo Data Science. Con tutorials step-by-step e casi concreti cercherò di guidarvi all'interno del mondo Data Science con R.

Per ogni dubbio o richiesta di informazioni non esitate a contattarmi.

Io sono Alessio Passalacqua, se vuoi sapere chi sono visita la mia [pagina personale](https://alessiopassalacqua.github.io/passalacqua/).








