---
output:
  html_document: 
    toc: true
    toc_float: true
---

In questa pagina raccolto la mia libreria, i pachetti che uso maggiormente in R e quelli che ritengo più interessanti per il mio lavoro futuro.


[Quick list of useful R packages](https://support.rstudio.com/hc/en-us/articles/201057987-Quick-list-of-useful-R-packages?mobile_site=true)

[Great R packages for data import, wrangling and visualization](https://www.computerworld.com/article/2921176/business-intelligence/great-r-packages-for-data-import-wrangling-visualization.html#tk.drr_mlt)

[R resources (free courses, books, tutorials, & cheat sheets)](https://paulvanderlaken.com/2017/08/10/r-resources-cheatsheets-tutorials-books/)

[Top 20 R Libraries for Data Science in 2018 ](https://activewizards.com/blog/top-20-r-libraries-for-data-science-in-2018-infographic/)



# Get the data

R fornisce un intero [manuale](https://cran.r-project.org/doc/manuals/r-release/R-data.html) che descrive il processo di importazione/esportazione dei dati.

> readr


> rio

L'idea alla base di rio è quella di semplificare il processo di importazione dei dati in R ed esportazione dei dati da R. Questo processo è, probabilmente inutilmente, estremamente complesso per gli utenti R principianti. 

[rio - vignettes](https://cran.r-project.org/web/packages/rio/vignettes/rio.html)

## Connect to database


> dplyr

[Introduction to dbplyr - vignettes](https://cran.r-project.org/web/packages/dbplyr/vignettes/dbplyr.html)

> RPostgreSQL

Database interface and 'PostgreSQL' driver for 'R'.

# Trasformation

> forcats

L'obiettivo del pacchetto forcats è quello di fornire una suite di strumenti utili che risolvano i problemi più comuni con i fattori. 

[website](http://forcats.tidyverse.org/)



# Explorative data analysis

> GGally

ggpairs

> ggpubr


The ‘ggpubr’ package provides some easy-to-use functions for creating and customizing ‘ggplot2’- based publication ready plots.

[ggpubr: ‘ggplot2’ Based Publication Ready Plots](http://www.sthda.com/english/rpkgs/ggpubr/index.html)

> SmartEDA

Summarize and Explore the Data [vignettes](https://cran.r-project.org/web/packages/SmartEDA/vignettes/Report_r1.html)

SmartEDA include diverse funzioni personalizzate per eseguire un'analisi esplorativa iniziale su qualsiasi dato di input per descrivare la struttura e le relazioni presenti nei dati. Il risultato generato può essere ottenuto sia in forma sommaria che grafica. La forma grafica o i grafici possono essere esportati anche come report

> FunModeling

> DataExplorer

Processo di esplorazione dei dati per l'analisi dei dati e la creazione di modelli, in modo che gli utenti possano concentrarsi sulla comprensione dei dati e sull'estrazione di informazioni. Il pacchetto esegue automaticamente la scansione di ogni variabile ed esegue il profilo dati. Le tecniche grafiche tipiche saranno eseguite sia per le caratteristiche discrete che per quelle continue.


Tradotto con www.DeepL.com/Translator

[Introduction to DataExplorer - vignettes](https://cran.r-project.org/web/packages/DataExplorer/vignettes/dataexplorer-intro.html)

# Dimension Reduction (PCA)

> FactoMineR


# Vizualization






> ggplot2

[Top 50 ggplot2 Visualizations - The Master List (With Full R Code)](http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html)

> tabplot

[Visualization of large datasets with tabplot](https://cran.r-project.org/web/packages/tabplot/vignettes/tabplot-vignette.html)


> plotly

> patchwork

L'obiettivo di [patchwork](https://github.com/thomasp85/patchwork/blob/master/README.md) è quello di rendere ridicolo per semplificare la combinazione di ggplots separati nella stessa grafica

# Modeling

> caret

> mlr

[Machine Learning in R: mlr Tutorial](https://mlr-org.github.io/mlr-tutorial/release/html/index.html)

> iml

I modelli di machine learning superano ripetutamente i modelli parametrici interpretabili, come il modello di regressione lineare. I guadagni in termini di prestazioni hanno un prezzo: I modelli funzionano come scatole nere non interpretabili.

Fortunatamente, ci sono molti metodi che possono rendere interpretabili i modelli di apprendimento automatico. Il pacchetto R iml fornisce strumenti per l'analisi di qualsiasi modello machine-learning balckbox:

Importanza della caratteristica: Quali erano le caratteristiche più importanti?

Effetti caratteristici: In che modo una funzione influenza la previsione? (Piazzole a dipendenza parziale e curve di aspettativa condizionali individuali)

Spiegazioni per le singole previsioni: In che modo i valori delle caratteristiche di un singolo punto dati hanno influenzato la sua previsione? (valore LIME e Shapley)

> lime

> xgboostExplaine

[xgboostExplainer](https://medium.com/applied-data-science/new-r-package-the-xgboost-explainer-51dd7d1aa211) makes your XGBoost model as transparent and 'white-box' as a single decision tree


[Interpretable Machine Learning with iml and mlr](https://mlr-org.github.io/interpretable-machine-learning-iml-and-mlr/)


> shinyMlr

[github](https://github.com/mlr-org/shinyMlr)

Integration of the mlr package into shiny.
With help of this package mlr can be accessed via a shiny interface.

[video tutorial](https://www.youtube.com/watch?v=VZuRSQZdayY&list=PLcTJ-34ghaH2QGL73DWfQvIdacW01Nvtp)

> bounceR

The R package bounceR ([github](https://github.com/STATWORX/bounceR)) provides methods and tools for automated feature selection for Machine Learning models. The methods are fit for situation in which the data scientists faces an exceedingly high number of features.

# Deep Learning

[Deep Learning in R](http://www.rblog.uni-freiburg.de/2017/02/07/deep-learning-in-r/)



# R Interface



> sparkrl


> RWeka

RWeka è un'interfaccia R a Weka. Weka è una raccolta di algoritmi di apprendimento automatico per attività di data mining scritti in Java, contenenti strumenti per la preelaborazione, classificazione, regressione, clustering, regole di associazione e visualizzazione dei dati. 

[cran](https://cran.r-project.org/web/packages/RWeka/index.html)

[Image Classification on Small Datasets with Keras](https://tensorflow.rstudio.com/blog/keras-image-classification-on-small-datasets.html)

> rbokeh

[rbokeh - R Interface for Bokeh](http://hafen.github.io/rbokeh/#background)
Bokeh is a visualization library that provides a flexible and powerful declarative framework for creating web-based plots. Bokeh renders plots using HTML canvas and provides many mechanisms for interactivity.

## Deep Learning interface

> h2o

[The one function call you need to know as a data scientist: h2o.automl](https://longhowlam.wordpress.com/2017/08/30/the-one-function-call-you-need-to-know-as-a-data-scientist-h2o-automl/)

[Classification and Regression with H2O Deep Learning - github](https://github.com/h2oai/h2o-tutorials/tree/master/tutorials/deeplearning)

> Keras

[website](https://tensorflow.rstudio.com/keras/)


> 

R notebooks for the code samples of the book "Deep Learning with R"

[deep-learning-with-r-notebooks](https://github.com/jjallaire/deep-learning-with-r-notebooks)

# Big-Data

> ff

Il pacchetto ff fornisce strutture dati che sono memorizzate su disco ma si comportano (quasi) come se fossero in RAM mappando in modo trasparente solo una sezione (pagesize) nella memoria principale - l'effettivo consumo di memoria virtuale per oggetto ff.

> bigml

# Deploy

> aurelius

PFA struscture 

[A Scalable Predictive API with PFA and AWS Lambda](https://stevenmortimer.com/a-scalable-predictive-api-with-pfa-and-aws-lambda/)

# Time series

> prophet

[prohet](https://facebook.github.io/prophet/) Strumento per produrre previsioni di alta qualità per le serie temporali di dati che hanno una stagionalità multipla con crescita lineare o non lineare.

# Reporting & Publishing results

> shiny

[An awesome R-shiny list!](https://grabear.github.io/awesome-rshiny/)

> shinydashboard

> rmarkdorwn

[icon: web icons for rmarkdown](https://ropensci.org/technotes/2018/05/15/icon/)

> ReporteRs


> kableExtra

Construct complex table with

[vignettes](https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html)

[website](https://davidgohel.github.io/ReporteRs/index.html)

# Six-Sigma 

> SixSigma

[Six Sigma DMAIC Series in R – Part 1](https://datascienceplus.com/six-sigma-dmaic-series-in-r-part-1/)

[Six Sigma with R - ebook](http://www.sixsigmawithr.com/)

[Quality Control with R](http://www.qualitycontrolwithr.com/)


> qcc



# DOE


# R API

> dockerfiler

{dockerfiler} is a package that comes with a simple, object oriented API for Dockerfile creation, straight from your R session. Now on CRAN. [tutorial](http://colinfay.me/dockerfiler-cran/)

> cloudML

[website](https://tensorflow.rstudio.com/tools/cloudml/articles/getting_started.html)


[Services and tools for building intelligent R applications in the cloud](http://blog.revolutionanalytics.com/2018/01/r-cloud-tools.html)

[Working with APIs from R](https://stevenmortimer.com/presentations/working-with-apis-from-r/)

[2017-11-18-API-Development-with-R-Part-I](http://jaehyeon-kim.github.io/2017/11/API-Development-with-R-Part-I.html)

> googleComputeEngineR 

provides an R interface to the Google Cloud Compute Engine API, for launching virtual machines.

# IDE

> Rcode

# Altro

> MonetDBLite

MonetDBLite for R, a fully embedded version of MonetDB that installs like any other R package. The database runs within the R process itself (like its namesake SQLite), greatly improving efficiency of data transfers. The package is available for Linux, Mac OS X and Windows (64 bit). 

