---
output:
  html_document: 
    toc: true
    toc_float: true
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

<link rel="stylesheet" href="styles.css" type="text/css">

## Installazione di R e RStudio

Per installare l’ultima versione di R bisogna andare sulla pagina [CRAN] (https://cran.r-project.org/) e seguire le istruzioni per il download.
Al termine del quale eseguire il file di installazione e seguire le istruzioni.

Istruzioni più dettagliate li potete trovare in questa presentazione che ho preparato e accessibile al seguente link.

Come tutti i linguaggi di programmazione è opportuno lavorare su un’interfaccia IDE, cioè un’applicazione grafica con una serie di strumenti che ci possano aiutare nello sviluppare ed eseguire il codice. RStudio è un ambiente di sviluppo integrato (IDE) per R. E’ un software open-source che gira su Linux, Mac OS X e Windows e può essere scaricato dal sito di [RStudio](http://www.rstudio.com)

## Avviare un progetto di RStudio




## Oggetti e Funzioni

Per sfruttare al meglio il linguaggio R, è necessaria una solida comprensione dei tipi di dati di base e delle strutture dei dati e di come operare su di essi.

E' molto importante capire perché questi sono considerati oggetti che vengono manipolate attraverso una funzione.

Tutto è una funzione, dal calcolo della media da un algoritmo di deeplearning


Tutto ciò che esiste è un oggetto.
Tutto ciò che accade è una chiamata di funzione.

## Le strutture di dati

I dati sono conetuti in oggetti

## I comandi di base

c, help, #

## Tipi di dati

* Carattere
* Numerico
* Intero
* Logico
* Complesso



